language: node_js
sudo: false
node_js:
  - 6.11.1
env:
  - NODE_ENV="test"
before_script:
  - yarn db:setup:user
  - yarn db:reset
  - psql --username postgres --dbname sfmovies_test -c 'CREATE EXTENSION fuzzystrmatch;'
script:
  - yarn lint
  - yarn test
  - yarn enforce
